# Node.js 공식 이미지를 베이스 이미지로 사용
FROM node:latest

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사
COPY package.json package-lock.json* ./

# 프로젝트 의존성 설치
RUN npm install

# 프로젝트 파일 복사
COPY . .

# 컨테이너 실행 시 실행될 명령어
CMD ["npx", "tailwindcss", "-i", "./src/assets/styles/input.css", "-o", "./src/assets/styles/output.css"]
