services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    volumes:
      # - ./backend/nginx/src:/var/www/html
      - ./backend/nginx/logs:/var/log/nginx
      - ./frontend/src:/var/www/html
    init: true
    ports:
      - "$NGINX_PORT:$NGINX_PORT"
    env_file:
      - .env
    networks:
      - our_net
    depends_on:
      django:
        condition: service_healthy

  django:
    image: django
    container_name: django
    build:
      context: ./backend/django
      dockerfile: Dockerfile
    volumes:
      - ./backend/django/src:/django
    init: true
    ports:
      - "$DJANGO_PORT:$DJANGO_PORT"
    env_file:
      - .env
    networks:
      - our_net
    healthcheck:
      test: curl --fail http://$DJANGO_HOST:$DJANGO_PORT/health/ && curl --fail http://$DJANGO_HOST:$WS_PORT/health/
      interval: 3s
      timeout: 2s
      retries: 30
    depends_on:
      postgresql:
        condition: service_healthy
      redis-cache:
        condition: service_healthy

  redis-cache:
    image: redis-cache
    container_name: redis-cache
    build:
      context: ./backend/redis-cache
      dockerfile: Dockerfile
    init: true
    env_file:
      - .env
    networks:
      - our_net
    healthcheck:
      test: redis-cli -h redis-cache ping
      interval: 3s
      timeout: 2s
      retries: 30

  postgresql:
    image: postgresql
    container_name: postgresql
    build:
      context: ./backend/PostgreSQL
      dockerfile: Dockerfile
    # volumes:
    #   -
    init: true
    env_file:
      - .env
    networks:
      - our_net
    healthcheck:
      test: pg_isready --dbname=$POSTGRES_DB --host=$POSTGRES_HOST --port=$POSTGRES_PORT --username=$POSTGRES_USER
      interval: 3s
      timeout: 2s
      retries: 30

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    build:
      context: ./backend/prometheus
      dockerfile: Dockerfile
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./backend/prometheus/web-config.yml:/etc/prometheus/web-config.yml
      - ./backend/prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    ports:
      - "$PROMETHEUS_PORT:$PROMETHEUS_PORT"
    env_file:
      - .env
    networks:
      - our_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    build: 
      context: ./backend/grafana
      dockerfile: Dockerfile
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "$GRAFANA_PORT:$GRAFANA_PORT"
    env_file:
      - .env
    networks:
      - our_net
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
     - 9100:9100
    environment:
     - "TZ=Asia/Seoul"
    restart: always
    networks:
      - our_net
    command:
     - '--collector.disable-defaults'
     - '--collector.cpu'
     - '--collector.loadavg'

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-prometheus-exporter
    restart: always
    networks:
      - our_net
    command:
     - '--nginx.scrape-uri=https://$NGINX_HOST:$NGINX_PORT/metrics'

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    restart: always
    env_file:
      - .env
    networks:
      - our_net

volumes:
  prometheus_data:
  grafana_data:

networks:
  our_net:
    name: taeypark_hyeoan_network
    driver: bridge
