{
 "title": "Transcendence",
 "description": "postgresql, nginx, django, cpu 사용량 대시보드",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transcendence DB 바이트",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_database_size_bytes{datname=\"Transcendence_db\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "nginx request 합계",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "nginx keep-alive 수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      { "expr": "nginx_connections_active", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "django",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "django 접속 시도 수",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "django_http_requests_before_middlewares_total",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu 사용량",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}